package CapaPresentacion;

import CapaDatos.UsuarioDAO;
import CapaLogica.modelos.Administrativo;
import CapaLogica.modelos.Docente;
import CapaLogica.modelos.Estudiante;
import CapaLogica.modelos.Usuario;
import Recursos.componentes.Funciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernandez Logica || Farro UI
 */
public class frmManUsuario extends javax.swing.JFrame {

    private UsuarioDAO usuarioDAO;

    /**
     * Creates new form frmManUsuario
     */
    public frmManUsuario() {
        initComponents();
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"CODIGO", "NOMBRES", "DNI", "ROL", "FILA"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaUsuarios.setModel(modelo);
        usuarioDAO = new UsuarioDAO();
        listado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new Recursos.componentes.GradientPanel(new java.awt.Color(245, 247, 252), new java.awt.Color(230, 235, 253));
        jPanel1 = new Recursos.componentes.RoundedPanel(20);
        jLabel1 = new javax.swing.JLabel();
        txtDni = new Recursos.componentes.RoundedTextField(15);
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new Recursos.componentes.RoundedTextField(15);
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombres = new Recursos.componentes.RoundedTextField(15);
        txtDatoExtra = new Recursos.componentes.RoundedTextField(15);
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboTipoUsr = new Recursos.componentes.RoundedComboBox();
        btnRegistrar = new Recursos.componentes.RoundedButton(new java.awt.Color(84,73,229), new java.awt.Color(131,89,244), 20,0)
        ;
        btnActualizar = new Recursos.componentes.RoundedButton(new java.awt.Color(255,255,255), new java.awt.Color(255,255,255), 20,1);
        btnBuscar = new Recursos.componentes.RoundedButton(new java.awt.Color(255,255,255), new java.awt.Color(255,255,255), 20,1);
        btnEliminar = new Recursos.componentes.RoundedButton(new java.awt.Color(255,255,255), new java.awt.Color(255,255,255), 20,1);
        lblDatoExtra = new javax.swing.JLabel();
        jScrollPane1 = jScrollPane1 = new Recursos.componentes.RoundedScrollPane(tablaUsuarios, 20);
        tablaUsuarios = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel1.setText("Nombre Completo");

        jLabel4.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel4.setText("DNI:");

        jLabel6.setFont(new java.awt.Font("Adwaita Sans", 0, 14)); // NOI18N
        jLabel6.setText("Datos Personales");

        txtDatoExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoExtraActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel9.setText("Código:");

        jLabel10.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel10.setText("Tipo de Usuario");

        comboTipoUsr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --", "Estudiante", "Docente", "Administrativo" }));
        comboTipoUsr.setBorder(null);
        comboTipoUsr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoUsrItemStateChanged(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(232, 231, 231));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/agregar.png"))); // NOI18N
        btnRegistrar.setText("Registrarse");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(232, 231, 231));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(232, 231, 231));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(232, 231, 231));
        btnEliminar.setForeground(new java.awt.Color(255, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblDatoExtra.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDatoExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDatoExtra))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDni)))
                        .addComponent(comboTipoUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(txtCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipoUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatoExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatoExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 420, 540));

        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);
        if (tablaUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(2).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(3).setResizable(false);
        }

        Recursos.componentes.EstiloTablas.aplicarEstilo(tablaUsuarios);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 620, 540));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel7.setText("Usuarios Registrados");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Administra a Estudiantes, Docentes y Personal Administrativo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel11.setText("REGISTRO DE USUARIOS");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (txtCodigo.getText().isEmpty()
            || txtNombres.getText().isEmpty()
            || txtDni.getText().isEmpty()
            || txtDatoExtra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falta datos",
                "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String tipo = comboTipoUsr.getSelectedItem().toString();
            String id = txtCodigo.getText();
            String nom = txtNombres.getText();
            String dni = txtDni.getText();
            String dato = txtDatoExtra.getText();

            Usuario nuevo = null;

            if (tipo.equalsIgnoreCase("Estudiante")) {
                nuevo = new Estudiante(id, nom, dni, dato);
            } else if (tipo.equalsIgnoreCase("Docente")) {
                nuevo = new Docente(id, nom, dni, dato);
            } else if (tipo.equalsIgnoreCase("Administrativo")) {
                nuevo = new Administrativo(id, nom, dni, dato);
            }

            if (usuarioDAO.agregar(nuevo)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Usuario Registrado con exito",
                    "Mensaje",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpiar();
                listado();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Error: El CODIGO o DNI ya existe",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (txtCodigo.getText().isEmpty()
            || txtNombres.getText().isEmpty()
            || txtDni.getText().isEmpty()
            || txtDatoExtra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falta datos",
                "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            String id = txtCodigo.getText();
            String nom = txtNombres.getText();
            String dni = txtDni.getText();
            String tipo = comboTipoUsr.getSelectedItem().toString();
            String dato = txtDatoExtra.getText();

            Usuario editado = null;

            if (tipo.equals("Estudiante")) {
                editado = new Estudiante(id, nom, dni, dato);
            } else if (tipo.equals("Docente")) {
                editado = new Docente(id, nom, dni, dato);
            } else if (tipo.equals("Administrativo")) {
                editado = new Administrativo(id, nom, dni, dato);
            }

            if (usuarioDAO.actualizar(editado)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Usuario actualizado con exito",
                    "Mensaje",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpiar();
                listado();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No se pudo actualizar",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Se requiere el codigo del usuario",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        } else {
            String codigo = txtCodigo.getText();
            Usuario objUsu = UsuarioDAO.buscar(codigo);

            if (objUsu != null) {
                txtCodigo.setText(objUsu.getId());
                txtNombres.setText(objUsu.getNombres());
                txtDni.setText(objUsu.getDni());

                if (objUsu instanceof Estudiante) {
                    comboTipoUsr.setSelectedItem("Estudiante");
                    lblDatoExtra.setText("Carrera ");
                    txtDatoExtra.setText(((Estudiante) objUsu).getCarrera());
                } else if (objUsu instanceof Docente) {
                    comboTipoUsr.setSelectedItem("Docente");
                    lblDatoExtra.setText("Facultad ");
                    txtDatoExtra.setText(((Docente) objUsu).getFacultad());
                } else if (objUsu instanceof Administrativo) {
                    comboTipoUsr.setSelectedItem("Administrativo");
                    lblDatoExtra.setText("Area ");
                    txtDatoExtra.setText(((Administrativo) objUsu).getArea());
                }
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Usuario no encontrado",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
                limpiar();
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            String id = txtCodigo.getText();
            String cadena = "¿Estas seguro de eliminar " + txtNombres.getText() + "?";
            int respuesta = Funciones.dialogoPregunta(cadena);

            if (usuarioDAO.eliminar(id)) {
                if (respuesta == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(
                        this,
                        "Usuario eliminado",
                        "Mensaje",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    listado();
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(
                    this,
                    "Usuario no encontrado",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        int fila = tablaUsuarios.getSelectedRow();
        String codigo = tablaUsuarios.getValueAt(fila, 0).toString();
        txtCodigo.setText(codigo);
        btnBuscarActionPerformed(null);
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void comboTipoUsrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoUsrItemStateChanged
        String seleccion = comboTipoUsr.getSelectedItem().toString();

        switch (seleccion) {
            case "Estudiante" ->
                lblDatoExtra.setText("Carrera");
            case "Docente" ->
                lblDatoExtra.setText("Facultad");
            case "Administrativo" ->
                lblDatoExtra.setText("Area");
        }
    }//GEN-LAST:event_comboTipoUsrItemStateChanged

    private void txtDatoExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoExtraActionPerformed

    private void listado() {
        DefaultTableModel modelo = (DefaultTableModel) tablaUsuarios.getModel();
        modelo.setRowCount(0);

        Usuario[] datos = UsuarioDAO.obtener();
        int cantidad = UsuarioDAO.getCantidad();

        for (int i = 0; i < cantidad; i++) {
            Usuario objUsu = datos[i];
            String datoExtra = "";

            if (objUsu instanceof Estudiante estudiante) {
                datoExtra = estudiante.getCarrera();
            } else if (objUsu instanceof Docente docente) {
                datoExtra = docente.getFacultad();
            } else if (objUsu instanceof Administrativo administrativo) {
                datoExtra = administrativo.getArea();
            }

            if (objUsu != null) {
                modelo.addRow(new Object[]{
                    objUsu.getId(),
                    objUsu.getNombres(),
                    objUsu.getDni(),
                    objUsu.getRol(),
                    datoExtra
                });
            }
        }
    }

    private void limpiar() {
        txtCodigo.setText("");
        txtNombres.setText("");
        txtDni.setText("");
        txtDatoExtra.setText("");
        comboTipoUsr.setSelectedIndex(0);
        lblDatoExtra.setText("");
        txtCodigo.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboTipoUsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDatoExtra;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDatoExtra;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
