package CapaPresentacion;

import CapaDatos.LibroDAO;
import CapaLogica.modelos.Libro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauricio
 */
public class jdAniadirLibro extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdAniadirLibro.class.getName());

    /**
     * Creates new form jdAniadirLibro
     */
    public jdAniadirLibro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new Recursos.componentes.RoundedTextField(15);
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLIbros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaLIbros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaLIbros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLIbrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaLIbros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaLIbrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLIbrosMouseClicked
        String cod = tablaLIbros.getValueAt(tablaLIbros.getSelectedRow(), 0).toString();
        pasarDatos(cod);
         
        
    }//GEN-LAST:event_tablaLIbrosMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLIbros;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void listado() {
        String estado;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Titulo");
        modelo.addColumn("Autor");
        modelo.addColumn("Editorial");
        modelo.addColumn("Publicacion");
        modelo.addColumn("Categoria");
        modelo.addColumn("Estado");

        Libro[] datos = LibroDAO.obtener();
        int cantidad = LibroDAO.getCantidad();

        for (int i = 0; i < cantidad; i++) {
            Libro objLibro = datos[i];

            if (objLibro != null) {
                estado = objLibro.isDisponible() ? "Disponible" : "No disponible";
                modelo.addRow(new Object[]{
                    objLibro.getId(),
                    objLibro.getTitulo(),
                    objLibro.getAutor(),
                    objLibro.getEditorial(),
                    objLibro.getApublicacion(),
                    objLibro.getCategoria(),
                    estado
                });
            }
        }
        tablaLIbros.setModel(modelo);
    }
    
    
    private void pasarDatos(String id) {
        try {
             Libro objLibro = LibroDAO.getElemento(id);
//            //int stock = objLibro.getStock();
//            if (ctd <= stock) {
//                prod = cod;
//                cant = ctd;
//                String descuento = String.valueOf(JOptionPane.showInputDialog(rootPane,
//                    "Ingrese el porcentaje de descuento: ", "0"));
//
//                try {
//                    desc = Integer.parseInt(descuento);
//                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
//                }
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Stock insuficiente");
//            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

}
