
package CapaPresentacion;

import CapaDatos.LibroDAO;
import CapaDatos.UsuarioDAO;
import CapaLogica.modelos.Usuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauricio
 */
public class jdAniadirUsuario extends javax.swing.JDialog {
    private int libro = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdAniadirUsuario.class.getName());
    private jdPrestamoLibros ventanaPadre;

    /**
     * Creates new form jdAniadirUsuario
     */
    public jdAniadirUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        if (parent instanceof jdPrestamoLibros) {
            this.ventanaPadre = (jdPrestamoLibros) parent;
        }
        initComponents();
        listarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Recursos.componentes.GradientPanel(new java.awt.Color(245, 247, 252), new java.awt.Color(230, 235, 253));
        txtCodUsr = new Recursos.componentes.RoundedTextField(15);
        jScrollPane1 = new Recursos.componentes.RoundedScrollPane(tablaUsr, 20);
        tablaUsr = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaUsr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaUsr);

        Recursos.componentes.EstiloTablas.aplicarEstilo(tablaUsr);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(txtCodUsr))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtCodUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaUsrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsrMouseClicked
        int fila = tablaUsr.getSelectedRow();
        
        if (fila != -1 && ventanaPadre != null) {
            String idUsuario = tablaUsr.getValueAt(fila, 0).toString();
            String nombreUsuario = tablaUsr.getValueAt(fila, 1).toString();
            ventanaPadre.txtNombreUsuario.setText(nombreUsuario);
            ventanaPadre.idSeleccionado = idUsuario;
            this.dispose();
        }
    }//GEN-LAST:event_tablaUsrMouseClicked

    private void txtCodUsrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodUsrKeyReleased
        filtrarUsuarios();
    }//GEN-LAST:event_txtCodUsrKeyReleased

    private void listarProductos() {
        String estado;
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombres");
        modelo.addColumn("Dni");
        modelo.addColumn("Rol");
        
        Usuario[] datos = UsuarioDAO.obtener();
        int cantidad = UsuarioDAO.getCantidad();
        
        for (int i = 0; i < cantidad; i++) {
            Usuario objUsu = datos[i];
            
            if (objUsu != null) {
                modelo.addRow( new Object[] {
                    objUsu.getId(),
                    objUsu.getNombres(),
                    objUsu.getDni(),
                    objUsu.getRol()
                });
            }
        }
        tablaUsr.setModel(modelo);
    }

    private void filtrarUsuarios() {
        String filtro = txtCodUsr.getText().toLowerCase().trim();
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombres");
        modelo.addColumn("Dni");
        modelo.addColumn("Rol");
        
        Usuario[] datos = UsuarioDAO.obtener();
        int cantidad = UsuarioDAO.getCantidad();
        
        for (int i = 0; i < cantidad; i++) {
            Usuario objUsu = datos[i];
            
            if (objUsu != null) {
                String nombre = objUsu.getNombres().toLowerCase();
                
                if (filtro.isEmpty() || nombre.contains(filtro)) {
                    modelo.addRow(new Object[] {
                        objUsu.getId(),
                        objUsu.getNombres(),
                        objUsu.getDni(),
                        objUsu.getRol()
                    });
                }
            }
        }
        tablaUsr.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsr;
    private javax.swing.JTextField txtCodUsr;
    // End of variables declaration//GEN-END:variables
}
