package CapaPresentacion;

import CapaDatos.PrestamoDAO;
import CapaLogica.modelos.Prestamo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauricio
 */
public class jdBuscarPrestamo extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdBuscarPrestamo.class.getName());
    private jdDevolucionLibro ventanaPadre;

    /**
     * Creates new form jdBuscarPrestamo
     */
    public jdBuscarPrestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        if (parent instanceof jdDevolucionLibro) {
            this.ventanaPadre = (jdDevolucionLibro) parent;
        }
        initComponents();
        listarPrestamos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodUsr = new Recursos.componentes.RoundedTextField(15);
        jScrollPane1 = new Recursos.componentes.RoundedScrollPane(tablaPrestamos, 20);
        tablaPrestamos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCodUsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodUsrKeyReleased(evt);
            }
        });

        tablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPrestamos);

        Recursos.componentes.EstiloTablas.aplicarEstilo(tablaPrestamos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addComponent(txtCodUsr))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtCodUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPrestamosMouseClicked
        int fila = tablaPrestamos.getSelectedRow();
        if (fila != -1 && ventanaPadre != null) {
            String idPrestamo = tablaPrestamos.getValueAt(fila, 0).toString();
            String nombreLibro = tablaPrestamos.getValueAt(fila, 1).toString();
            
            ventanaPadre.idPrestamoSeleccionado = idPrestamo;
            ventanaPadre.cargarPrestamo(idPrestamo);
            this.dispose();
        }
    }//GEN-LAST:event_tablaPrestamosMouseClicked

    private void txtCodUsrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodUsrKeyReleased
        filtrarPrestamos();
    }//GEN-LAST:event_txtCodUsrKeyReleased

    private void listarPrestamos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Libro");
        modelo.addColumn("Usuario");
        modelo.addColumn("Fecha Salida");
        modelo.addColumn("Estado");

        Prestamo[] datos = PrestamoDAO.obtener();
        int cantidad = PrestamoDAO.getCantidad();

        for (int i = 0; i < cantidad; i++) {
            Prestamo p = datos[i];
            if (p != null) {
                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getLibro().getTitulo(),
                    p.getUsuario().getNombres(),
                    p.getFechaSalida(),
                    p.isEstado() ? "Activo" : "Finalizado"
                });
            }
        }
        tablaPrestamos.setModel(modelo);
    }

    private void filtrarPrestamos() {
        String filtro = txtCodUsr.getText().toLowerCase().trim();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Libro");
        modelo.addColumn("Usuario");
        modelo.addColumn("Fecha Salida");
        modelo.addColumn("Estado");

        Prestamo[] datos = PrestamoDAO.obtener();
        int cantidad = PrestamoDAO.getCantidad();

        for (int i = 0; i < cantidad; i++) {
            Prestamo p = datos[i];
            if (p != null) {
                String id = p.getId().toLowerCase();
                String libro = p.getLibro().getTitulo().toLowerCase();
                String usuario = p.getUsuario().getNombres().toLowerCase();

                if (filtro.isEmpty() || id.contains(filtro) || libro.contains(filtro) || usuario.contains(filtro)) {
                    modelo.addRow(new Object[]{
                        p.getId(),
                        p.getLibro().getTitulo(),
                        p.getUsuario().getNombres(),
                        p.getFechaSalida(),
                        p.isEstado() ? "Activo" : "Finalizado"
                    });
                }
            }
        }
        tablaPrestamos.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jdBuscarPrestamo dialog = new jdBuscarPrestamo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPrestamos;
    private javax.swing.JTextField txtCodUsr;
    // End of variables declaration//GEN-END:variables
}
