package CapaPresentacion;

import CapaDatos.PrestamoDAO;
import CapaLogica.modelos.Prestamo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernandez Logica || Farro UI
 */
public class jdDevolucionLibro extends javax.swing.JFrame {
    public String idPrestamoActual = "";

    /**
     * Creates new form jdDevolcionLibro
     */
    public jdDevolucionLibro() {
        initComponents();
        listado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new Recursos.componentes.GradientPanel(new java.awt.Color(245, 247, 252), new java.awt.Color(230, 235, 253));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idPrestamoSeleccionado = new Recursos.componentes.RoundedTextField(15);
        jLabel4 = new javax.swing.JLabel();
        btnDevolver = new Recursos.componentes.RoundedButton(new java.awt.Color(84,73,229), new java.awt.Color(131,89,244), 20,0)
        ;
        btnBuscarUsuario = new Recursos.componentes.CircularButton("/Recursos/Assets/buscar2.png");
        btnBuscarUsuario1 = new Recursos.componentes.CircularButton("/Recursos/Assets/limpiar.png");
        jScrollPane4 = new Recursos.componentes.RoundedScrollPane(tablaDevoluciones, 20);
        tablaDevoluciones1 = new javax.swing.JTable();
        jScrollPane2 = new Recursos.componentes.RoundedScrollPane(tablaDevoluciones, 20);
        tablaDevoluciones = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Gestión rápida de retornos de biblioteca");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel3.setText("Devolución de Libros");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 10, 60));

        jPanel3.setBackground(new java.awt.Color(248, 250, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel1.setText("Detalles de la devolucion");

        jLabel4.setFont(new java.awt.Font("Adwaita Sans", 0, 12)); // NOI18N
        jLabel4.setText("Nombre Libro");

        btnDevolver.setBackground(new java.awt.Color(51, 0, 255));
        btnDevolver.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/devolver.png"))); // NOI18N
        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnBuscarUsuario.setBackground(new java.awt.Color(51, 51, 255));
        btnBuscarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarUsuarioLayout = new javax.swing.GroupLayout(btnBuscarUsuario);
        btnBuscarUsuario.setLayout(btnBuscarUsuarioLayout);
        btnBuscarUsuarioLayout.setHorizontalGroup(
            btnBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnBuscarUsuarioLayout.setVerticalGroup(
            btnBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btnBuscarUsuario1.setBackground(new java.awt.Color(131, 89, 244));

        javax.swing.GroupLayout btnBuscarUsuario1Layout = new javax.swing.GroupLayout(btnBuscarUsuario1);
        btnBuscarUsuario1.setLayout(btnBuscarUsuario1Layout);
        btnBuscarUsuario1Layout.setHorizontalGroup(
            btnBuscarUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        btnBuscarUsuario1Layout.setVerticalGroup(
            btnBuscarUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        tablaDevoluciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablaDevoluciones1);

        Recursos.componentes.EstiloTablas.aplicarEstilo(tablaDevoluciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(673, 673, 673)
                        .addComponent(btnBuscarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idPrestamoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idPrestamoSeleccionado)
                        .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        tablaDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaDevoluciones);

        Recursos.componentes.EstiloTablas.aplicarEstilo(tablaDevoluciones);

        jLabel7.setFont(new java.awt.Font("Adwaita Sans", 0, 13)); // NOI18N
        jLabel7.setText("Devoluciones Recientes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 770, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioMouseClicked
        jdBuscarPrestamo obj = new jdBuscarPrestamo(this, true);
        obj.setVisible(true);
    }//GEN-LAST:event_btnBuscarUsuarioMouseClicked

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // Validar que se haya buscado un préstamo
        if (idPrestamoSeleccionado.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Debe buscar un préstamo para devolver", 
                "Validación", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Obtener el ID del préstamo desde la tabla de detalles
        if (tablaDevoluciones1.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No hay préstamo seleccionado", 
                "Validación", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String idPrestamo = tablaDevoluciones1.getValueAt(0, 0).toString();
        
        // Confirmar la devolución
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de registrar la devolución del libro?", 
            "Confirmar devolución", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            boolean exito = CapaLogica.Servicio.BibliotecaService.devolverPrestamo(idPrestamo);
            
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Devolución registrada exitosamente", 
                    "Éxito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                // Limpiar campos
                idPrestamoActual = "";
                idPrestamoSeleccionado.setText("");
                DefaultTableModel modeloVacio = new DefaultTableModel();
                tablaDevoluciones1.setModel(modeloVacio);
                
                // Actualizar listado de devoluciones
                listado();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error al registrar la devolución. El préstamo ya fue devuelto o no existe.", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    public void cargarPrestamo(String id) {
        Prestamo p = PrestamoDAO.getElemento(id);
        if (p != null) {
            idPrestamoActual = id;
            idPrestamoSeleccionado.setText(p.getLibro().getTitulo());
            
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Libro");
            modelo.addColumn("Usuario");
            modelo.addColumn("Fecha Salida");
            modelo.addColumn("F. Devolución");
            
            modelo.addRow(new Object[]{
                p.getId(),
                p.getLibro().getTitulo(),
                p.getUsuario().getNombres(),
                p.getFechaSalida(),
                p.getFechaDevolucion()
            });
            tablaDevoluciones1.setModel(modelo);
        }
    }
    
    private void listado() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Usuario");
        modelo.addColumn("F Prestamo");
        modelo.addColumn("F Devolucion");
        modelo.addColumn("Estado");

        Prestamo[] lista = PrestamoDAO.obtener();
        int total = PrestamoDAO.getCantidad();
        
        for (int i = 0; i < total; i++) {
            Prestamo p = lista[i];

            if (p != null && p.getLibro() != null && p.getUsuario() != null && !p.isEstado()) {
                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getLibro().getTitulo(),
                    p.getUsuario().getNombres(),
                    p.getFechaSalida(),
                    p.getFechaDevolucion(),
                    (p.isEstado()) ? "Prestado" : "Devuelto"
                });
            }
        }
        tablaDevoluciones.setModel(modelo);
        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscarUsuario;
    private javax.swing.JPanel btnBuscarUsuario1;
    private javax.swing.JButton btnDevolver;
    public javax.swing.JTextField idPrestamoSeleccionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaDevoluciones;
    private javax.swing.JTable tablaDevoluciones1;
    // End of variables declaration//GEN-END:variables
}
